Namespace kudu/gutil down_cast() method to avoid conflict with mysql's down_cast()
Summary:
We want to be able to return error messages on sys var changes. In order to do that, we need to include <sql/sql_class.h> but this causes a method called down_cast to collide with kudu's method:

```
In file included from fbcode/mysql_raft/VarsStatus.cpp:24:
In file included from buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/sql/sql_class.h:46:
In file included from buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/m_ctype.h:43:
buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/template_utils.h:95:15: error: redefinition of 'down_cast'
   95 | inline Target down_cast(Source *arg) {
      |               ^
buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/kudu/gutil/__common__/buck-headers/kudu/gutil/casts.h:67:11: note: previous definition is here
   67 | inline To down_cast(From* f) { // so we only accept pointers
      |           ^
In file included from fbcode/mysql_raft/VarsStatus.cpp:24:
In file included from buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/sql/sql_class.h:46:
In file included from buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/m_ctype.h:43:
buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/mysql/server/__headers__/buck-headers/template_utils.h:116:15: error: redefinition of 'down_cast'
  116 | inline Target down_cast(Source &arg) {
      |               ^
buck-out/v2/gen/fbcode/7e6e6fbcbec1dd3c/kudu/gutil/__common__/buck-headers/kudu/gutil/casts.h:92:11: note: previous definition is here
   92 | inline To down_cast(From& f) {
      |           ^
2 errors generated.
Buck UI: https://www.internalfb.com/buck2/922f19d3-5c72-46b1-afb6-e713747df182
Network: Up: 11MiB  Down: 106MiB  (reSessionID-ba809b47-6591-4231-afda-5d4665d08a64)
```

To fix this, we can namespace the down_cast() method on kudu

Test Plan: sandcastle

Reviewed By: li-chi

Differential Revision: D72065153

fbshipit-source-id: 2c451434edeb6a048490af0186486a1c93a66d3d